---
title: "case_study"
author: "Kino Watanabe"
date: "2025-10-26"
output: html_document
---

```{r}
library(tidyverse)
library(p8105.datasets)
library(leaflet)
data(nyc_airbnb)
     
     
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

Let's look at prices first
```{r}
nyc_airbnb |> 
  drop_na(price) |> 
  group_by(neighbourhood_group) |> 
  summarise(
    mean_price = mean(price),
    min_price = min(price),
    max_price = max(price)
    )
```
what about price in a given neighborhood?
```{r}
nyc_airbnb |> 
  drop_na(price) |> 
  filter(neighbourhood_group == "Manhattan") |> 
  group_by(room_type) |>  
  summarise(
    mean_price = mean(price),
    min_price = min(price),
    max_price = max(price)
    )
```

average price of a room type in each neighboorhood 
```{r}
nyc_airbnb |> 
  drop_na(price) |> 
  group_by(room_type, neighbourhood_group) |>  
  summarise(
    mean_price = mean(price),
    min_price = min(price),
    max_price = max(price)
    )

# clean up 
nyc_airbnb |> 
  drop_na(price) |> 
  group_by(room_type, neighbourhood_group) |>  
  summarise(
    mean_price = mean(price)
    ) |> 
  pivot_wider(
    names_from = room_type,
    values_from = mean_price
  )
```


```{r}
nyc_airbnb |> 
  count(neighbourhood_group, room_type)
```

make some plots
```{r}
nyc_airbnb|> 
  ggplot(aes(x = price)) +
  geom_histogram() +
  facet_grid(room_type ~ neighbourhood_group) +
  scale_x_continuous(limits = c(0, 1000))
```


```{r}
nyc_airbnb |> 
  filter(
    neighbourhood_group == "Manhattan",
    price < 500, 
    room_type == "Entire home/apt"
  ) |> 
  mutate(
    neighbourhood = fct_reorder(neighbourhood, price)
  ) |> 
  ggplot(aes(x = neighbourhood, y = price)) +
  geom_violin() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))
```

**remember to look at extreme values**

```{r}
nyc_airbnb |> 
  filter(price > 9000)
```
```{r}
nyc_airbnb |> 
  filter(calculated_host_listings_count > 30)
```


keep looking at location
```{r}
nyc_airbnb |> 
  filter(
    neighbourhood_group == "Manhattan",
    price < 1000, 
    room_type == "Entire home/apt"
  ) |> 
  ggplot(aes(x = lat, y = long, color = price)) +
  geom_point()
```

# leaflet -- need to render to html_document instead of github_document

can we make a better map? leaflet package - interactive map
```{r}
# Create a continuous palette function
pal <- colorNumeric(
  palette = "viridis",
  domain = nyc_airbnb$price)

nyc_airbnb |> 
  filter(
    neighbourhood_group == "Manhattan",
    price < 1000, 
    room_type == "Entire home/apt") |> 
  sample_n(25) |> 
  leaflet() %>% 
    addTiles() |> 
  addMarkers(~long, ~lat)

nyc_airbnb |> 
  filter(
    neighbourhood_group == "Manhattan",
    price < 1000, 
    room_type == "Entire home/apt") |> 
  sample_n(25) |> 
  leaflet() %>% 
    addProviderTiles(providers$CartoDB.Positron) |> 
  addCircleMarkers(~long, ~lat,
                   color = ~pal(price),
                   radius = 2)
```

